-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# # WHERE PRODUCT_ID IN (
# #     SELECT PRODUCT_ID
# #     FROM ONLINE_SALE
# #     GROUP BY USER_ID
# #     HAVING COUNT(USER_ID) > 1
# # )

# ORDER BY USER_ID ASC, PRODUCT_ID DESC;
SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS purchase_count
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*) > 1
) AS ASD
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

