SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as 'SALES_DATE', PRODUCT_ID, NULL as 'USER_ID', SALES_AMOUNT
FROM OFFLINE_SALE as off_sale
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS 'SALES_DATE', PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE as on_sale
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;