SELECT B.PRODUCT_ID, B.PRODUCT_NAME, A.AMOUNT * B.PRICE as TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) as AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE,"%Y-%m") = "2022-05"
    GROUP BY PRODUCT_ID
) as A
JOIN FOOD_PRODUCT B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
