SELECT FH.FLAVOR
FROM (
    SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
) FH
JOIN (
    SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) JULY
ON JULY.FLAVOR = FH.FLAVOR
ORDER BY JULY.TOTAL_ORDER + FH.TOTAL_ORDER DESC
LIMIT 3;
