SELECT 
    APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, 
    APNT_YMD
FROM (PATIENT, DOCTOR)
JOIN (
    SELECT *
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND APNT_CNCL_YN = "N"
    AND MCDP_CD = "CS"
    ) A
ON A.PT_NO = PATIENT.PT_NO AND A.MDDR_ID = DOCTOR.DR_ID
ORDER BY APNT_YMD;