
# SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
# DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
# FROM USED_GOODS_BOARD as A
# INNER JOIN USED_GOODS_REPLY as B
# ON A.BOARD_ID = B.BOARD_ID
# WHERE DATE_FORMAT(B.CREATED_DATE, "%Y-%m") = "2022-10"
# ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;

SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') as 'CREATED_DATE'
FROM USED_GOODS_BOARD as a
INNER JOIN USED_GOODS_REPLY as b
ON a.BOARD_ID = b.BOARD_ID
WHERE a.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY b.CREATED_DATE, a.TITLE;